name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  elixir:
    name: Elixir (format, compile, test)
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      DATABASE_URL: sqlite3:podcodar_test.db
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18'
          otp-version: '28'

      - name: Cache Mix deps
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: mix-${{ runner.os }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            mix-${{ runner.os }}-

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3

      - name: Install Mix deps
        run: mix deps.get

      - name: Check formatting
        run: mix format --check-formatted

      - name: Compile with warnings as errors
        run: mix compile --warning-as-errors

      - name: Build assets
        run: mix assets.build

      - name: Run tests (incl. DB setup via alias)
        run: mix test

  scripts:
    name: Deno scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm

      - name: Install deps
        run: deno install

      - name: Linter is happy
        run: deno lint scripts/**

      - name: Tests are passing
        run: deno test

  quality-gateway:
    name: Quality Gateway
    needs: [elixir, scripts]
    runs-on: ubuntu-latest
    steps:
      - name: All checks passed
        run: echo "All required jobs succeeded."


